/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jack_armhello_NativeUitls */

#ifndef _Included_com_jack_armhello_NativeUitls
#define _Included_com_jack_armhello_NativeUitls
#ifdef __cplusplus
extern "C" {
#endif

#define DEBUG     //调试开关


typedef struct _funinfo{
	Elf32_Addr st_value;
	Elf32_Word st_size;
}funcInfo;

/*
 * Class:     com_jack_armhello_NativeUitls
 * Method:    getString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jack_armhello_NativeUitls_getString
  (JNIEnv *, jclass, jint);


static unsigned elfhash(const char *_name);

static unsigned int getLibAddr();

static void print_debug(const char *msg);

void init_decode();


static char getTargetFun(unsigned long base, const char *funname, funcInfo *info);

#ifdef __cplusplus
}
#endif
#endif
