/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jack_armhello_NativeUitls */

#include  <android/log.h>
#include <stdio.h>
#include <jni.h>
#ifndef _Included_com_jack_armhello_NativeUitls
#define _Included_com_jack_armhello_NativeUitls
#ifdef __cplusplus
extern "C" {
#endif

#define TAG "j_tag_native"

#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,TAG,__VA_ARGS__)
/*
 * Class:     com_jack_armhello_NativeUitls
 * Method:    getString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jack_armhello_NativeUitls_getString
  (JNIEnv *, jclass, jint);
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved);
JNIEXPORT void JNICALL JNI_OnUnload(JavaVM* vm, void* reserved);

/*
* java-native函数映射数组，数组参数意思分别是：
* java层函数名  Java层函数返回值  native层映射的名字
*/
jstring funNative(JNIEnv *env, jclass jobj, jint number);
static JNINativeMethod methods[]  = {{"registerFunNative", "(I)Ljava/lang/String;", (void *)funNative}};

#ifdef __cplusplus
}
#endif
#endif
