/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_xtu_GetString */

#ifndef _Included_com_example_xtu_GetString
#define _Included_com_example_xtu_GetString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_xtu_GetString
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_xtu_GetString_encrypt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_xtu_GetString
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_xtu_GetString_getString
  (JNIEnv *, jclass);

/*
 * Class:     com_example_xtu_GetString
 * Method:    sendData
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_xtu_GetString_sendData
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
